import type {
  MarkingCategoryDefinition,
  MarkingFieldDefinition,
} from "../../../shared/types";

/** Every category field renders inside the form's "categories" step. */
const withCategoryStep = (
  fields: Omit<MarkingFieldDefinition, "step">[]
): MarkingFieldDefinition[] =>
  fields.map((field) => ({ ...field, step: "categories" as const }));

/**
 * G1 2027 marking scheme — 100% of the source aloysius-g1 circular categories
 * (6.1–6.6), every scored field, grouped by the application form's steps
 * (location → applicant → guardian → residence → categories → declaration →
 * review). Map fields (`type: "map"`) carry the proximity deduction config:
 * the system counts schools inside the applicant's map circle and marks are
 * deducted per school.
 */

export const subversion1Categories: MarkingCategoryDefinition[] = [
  {
    type: "6.1",
    label: "Residence Verification & Proximity",
    description:
      "6.1 — Residence documents, electoral register and map proximity.",
    maxMarks: 100,
    // g1's application-store allows any category type to be added multiple times
    // (entries only need unique ids) — keep that behaviour.
    allowMultipleEntries: true,
    step: "categories",
    fields: withCategoryStep([
      {
        key: "mainDocumentType",
        label: "Main Residence Document",
        type: "select",
        required: true,
        group: "Residence Document",
        options: [
          "title-deed-applicant",
          "title-deed-parents",
          "feeder-electoral-5yrs",
          "lease-deed",
          "municipal-ds-certificate",
          "other-documents",
        ],
      },
      {
        key: "deedTransferDate",
        label: "Deed Transfer Date",
        type: "date",
        required: false,
        group: "Residence Document",
        visibleWhen: [
          {
            field: "mainDocumentType",
            in: ["title-deed-applicant", "title-deed-parents", "lease-deed"],
          },
        ],
      },
      {
        key: "additionalDocs",
        label: "Additional Supporting Documents",
        type: "list",
        required: false,
        group: "Residence Document",
      },
      {
        key: "electoralMotherYears",
        label: "Mother's Electoral Register Years",
        type: "list",
        required: false,
        group: "Electoral Register",
      },
      {
        key: "electoralFatherYears",
        label: "Father's Electoral Register Years",
        type: "list",
        required: false,
        group: "Electoral Register",
      },
      {
        key: "schoolsWithinRadius",
        label: "Nearby Schools (map circle)",
        type: "map",
        required: true,
        group: "Map Proximity",
        mapConfig: { maxMarks: 50, pointsPerSchool: 5, pointsKm: 10 },
      },
    ] satisfies Omit<MarkingFieldDefinition, "step">[]),
  },
  {
    type: "6.2",
    label: "Alumni",
    description:
      "6.2 — Past pupil's education, achievements and association membership.",
    maxMarks: 100,
    // g1's application-store allows any category type to be added multiple times
    // (entries only need unique ids) — keep that behaviour.
    allowMultipleEntries: true,
    step: "categories",
    fields: withCategoryStep([
      {
        key: "alumniStartDate",
        label: "Education Start",
        type: "date",
        required: true,
        group: "Education",
      },
      {
        key: "alumniEndDate",
        label: "Education End",
        type: "date",
        required: true,
        group: "Education",
      },
      {
        key: "grade5ScholarshipPassed",
        label: "Grade 5 Scholarship Passed",
        type: "boolean",
        required: false,
        group: "Education",
      },
      {
        key: "olSubjectCount",
        label: "O/L Subject Count",
        type: "select",
        required: false,
        group: "Education",
        options: ["6", "8", "9", "10"],
        clearsOnChange: ["olGradeS", "olGradeC", "olGradeB", "olGradeA"],
      },
      {
        key: "olGradeS",
        label: "O/L S Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "olSubjectCount", in: ["6", "8", "9", "10"] }],
      },
      {
        key: "olGradeC",
        label: "O/L C Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "olSubjectCount", in: ["6", "8", "9", "10"] }],
      },
      {
        key: "olGradeB",
        label: "O/L B Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "olSubjectCount", in: ["6", "8", "9", "10"] }],
      },
      {
        key: "olGradeA",
        label: "O/L A Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "olSubjectCount", in: ["6", "8", "9", "10"] }],
      },
      {
        key: "alSubjectCount",
        label: "A/L Subject Count",
        type: "select",
        required: false,
        group: "Education",
        options: ["3", "4"],
        clearsOnChange: ["alGradeS", "alGradeC", "alGradeB", "alGradeA"],
      },
      {
        key: "alGradeS",
        label: "A/L S Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "alSubjectCount", in: ["3", "4"] }],
      },
      {
        key: "alGradeC",
        label: "A/L C Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "alSubjectCount", in: ["3", "4"] }],
      },
      {
        key: "alGradeB",
        label: "A/L B Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "alSubjectCount", in: ["3", "4"] }],
      },
      {
        key: "alGradeA",
        label: "A/L A Grades",
        type: "number",
        required: false,
        group: "Education",
        visibleWhen: [{ field: "alSubjectCount", in: ["3", "4"] }],
      },
      {
        key: "sportsEntries",
        label: "Sports Achievements",
        type: "list",
        required: false,
        group: "Co-curricular",
      },
      {
        key: "leadershipRoles",
        label: "Leadership Roles",
        type: "list",
        required: false,
        group: "Co-curricular",
        options: [
          "prefect-primary",
          "prefect-junior",
          "prefect-senior",
          "deputy-head-prefect",
          "head-prefect",
          "first-team-vice-captain",
          "first-team-captain",
        ],
      },
      {
        key: "studentSocietiesEntries",
        label: "Student Societies",
        type: "list",
        required: false,
        group: "Co-curricular",
      },
      {
        key: "otherActivities",
        label: "Other Activities",
        type: "list",
        required: false,
        group: "Co-curricular",
        options: [
          "junior-band-leader",
          "junior-band-member",
          "senior-band-leader",
          "senior-band-member",
          "scout-leader",
          "scout-member",
          "cub-scout",
          "cadet-team-leader",
          "cadet-team-member",
          "debating-team-leader",
          "debating-team-member",
          "st-john-ambulance-leader",
          "st-john-ambulance-member",
          "other",
        ],
      },
      {
        key: "pastPupilsLifeMember",
        label: "Life Member of Past Pupils' Association",
        type: "boolean",
        required: false,
        group: "Past Pupils' Association",
      },
      {
        key: "pastPupilsLifeMemberStart",
        label: "Life Member Since",
        type: "date",
        required: false,
        group: "Past Pupils' Association",
        visibleWhen: [{ field: "pastPupilsLifeMember", in: [true] }],
      },
      {
        key: "pastPupilsMembershipStart",
        label: "Membership Start",
        type: "date",
        required: false,
        group: "Past Pupils' Association",
        visibleWhen: [{ field: "pastPupilsLifeMember", in: [false] }],
      },
      {
        key: "pastPupilsMembershipEnd",
        label: "Membership End",
        type: "date",
        required: false,
        group: "Past Pupils' Association",
        visibleWhen: [{ field: "pastPupilsLifeMember", in: [false] }],
      },
      {
        key: "pastPupilsCommitteeYears",
        label: "Committee Years",
        type: "number",
        required: false,
        group: "Past Pupils' Association",
      },
      {
        key: "pastPupilsExecutiveCount",
        label: "Executive Posts Held",
        type: "number",
        required: false,
        group: "Past Pupils' Association",
      },
      {
        key: "highestDegree",
        label: "Highest Degree",
        type: "select",
        required: false,
        group: "Higher Education",
        options: [
          "none",
          "first-degree",
          "postgraduate",
          "doctorate",
          "chartered-professional",
        ],
      },
      {
        key: "hasDiploma",
        label: "Holds Diploma / Higher Diploma",
        type: "boolean",
        required: false,
        group: "Higher Education",
      },
      {
        key: "carnivalContribution",
        label: "Carnival Contributions (count)",
        type: "number",
        required: false,
        group: "Contributions",
      },
      {
        key: "shramadanaContribution",
        label: "Shramadana Contributions (count)",
        type: "number",
        required: false,
        group: "Contributions",
      },
      {
        key: "otherContributionEntries",
        label: "Other Contributions",
        type: "list",
        required: false,
        group: "Contributions",
      },
      {
        key: "schoolProjectsContribution",
        label: "Contributed to School Projects",
        type: "boolean",
        required: false,
        group: "Contributions",
      },
      {
        key: "schoolProjectsDescription",
        label: "School Project Details",
        type: "text",
        required: false,
        group: "Contributions",
        visibleWhen: [{ field: "schoolProjectsContribution", in: [true] }],
      },
    ] satisfies Omit<MarkingFieldDefinition, "step">[]),
  },
  {
    type: "6.3",
    label: "Siblings",
    description:
      "6.3 — Sibling education at this school, achievements and parent cooperation.",
    maxMarks: 100,
    allowMultipleEntries: true,
    step: "categories",
    fields: withCategoryStep([
      {
        key: "siblingGradesCompletedCount",
        label: "Grades Completed by Sibling",
        type: "number",
        required: true,
        group: "Sibling Education",
      },
      {
        key: "siblingStudiedAtAppliedSchool",
        label: "Sibling Studied at Applied School",
        type: "boolean",
        required: false,
        group: "Sibling Education",
      },
      {
        key: "twoOrMoreSiblingsStudyingOtherGrades",
        label: "Two or More Siblings Studying in Other Grades",
        type: "boolean",
        required: false,
        group: "Sibling Education",
      },
      {
        key: "siblingSportsEntries",
        label: "Sibling Sports Achievements",
        type: "list",
        required: false,
        group: "Sibling Co-curricular",
      },
      {
        key: "siblingExamAchievements",
        label: "Sibling Exam Achievements",
        type: "list",
        required: false,
        group: "Sibling Co-curricular",
        options: ["scholarship", "ol", "al"],
      },
      {
        key: "siblingLeadershipAchievement",
        label: "Sibling Leadership (Prefect / Scout)",
        type: "boolean",
        required: false,
        group: "Sibling Co-curricular",
      },
      {
        key: "parentsSupportRendered",
        label: "Cooperation Shown by Parents",
        type: "boolean",
        required: false,
        group: "Parent Cooperation",
      },
      {
        key: "parentsSupportDescription",
        label: "Support Details",
        type: "text",
        required: false,
        group: "Parent Cooperation",
        visibleWhen: [{ field: "parentsSupportRendered", in: [true] }],
      },
      {
        key: "mainDocumentType",
        label: "Residence Document",
        type: "select",
        required: false,
        group: "Residence & Electoral",
        options: [
          "title-deed-applicant-spouse",
          "title-deed-parents",
          "feeder-electoral-5yrs",
          "lease-deed",
          "municipal-ds-rentact-cert",
          "other-documents",
        ],
      },
      {
        key: "electoralMotherYears",
        label: "Mother's Electoral Register Years",
        type: "list",
        required: false,
        group: "Residence & Electoral",
      },
      {
        key: "electoralFatherYears",
        label: "Father's Electoral Register Years",
        type: "list",
        required: false,
        group: "Residence & Electoral",
      },
      {
        key: "schoolsWithinRadius",
        label: "Nearby Schools (map circle)",
        type: "map",
        required: true,
        group: "Map Proximity",
        mapConfig: { maxMarks: 30, pointsPerSchool: 3, pointsKm: 10 },
      },
    ] satisfies Omit<MarkingFieldDefinition, "step">[]),
  },
  {
    type: "6.4",
    label: "Education Sector / Teaching Staff",
    description:
      "6.4 — Contribution to school education, service, difficult service and distances.",
    maxMarks: 100,
    // g1's application-store allows any category type to be added multiple times
    // (entries only need unique ids) — keep that behaviour.
    allowMultipleEntries: true,
    step: "categories",
    fields: withCategoryStep([
      {
        key: "contributionPath",
        label: "Contribution Path",
        type: "select",
        required: true,
        group: "School Education Contribution (7.5.1)",
        options: ["institution", "university"],
        clearsOnChange: [
          "contributionSameSchool",
          "contributionServiceStartDate",
          "contributionExamYears",
          "contributionCurriculumYears",
          "contributionTrainingYears",
        ],
      },
      {
        key: "contributionSameSchool",
        label: "Currently Serving at This School",
        type: "boolean",
        required: false,
        group: "School Education Contribution (7.5.1)",
        visibleWhen: [{ field: "contributionPath", in: ["institution"] }],
      },
      {
        key: "contributionServiceStartDate",
        label: "Service Start (Current Station)",
        type: "date",
        required: false,
        group: "School Education Contribution (7.5.1)",
        visibleWhen: [{ field: "contributionPath", in: ["institution"] }],
      },
      {
        key: "contributionExamYears",
        label: "National Exam Contribution Years",
        type: "number",
        required: false,
        group: "School Education Contribution (7.5.1)",
        visibleWhen: [{ field: "contributionPath", in: ["university"] }],
      },
      {
        key: "contributionCurriculumYears",
        label: "Curriculum Development Years",
        type: "number",
        required: false,
        group: "School Education Contribution (7.5.1)",
        visibleWhen: [{ field: "contributionPath", in: ["university"] }],
      },
      {
        key: "contributionTrainingYears",
        label: "Teacher Training Years",
        type: "number",
        required: false,
        group: "School Education Contribution (7.5.1)",
        visibleWhen: [{ field: "contributionPath", in: ["university"] }],
      },
      {
        key: "serviceStartDate",
        label: "Period of Service Start",
        type: "date",
        required: false,
        group: "Service",
      },
      {
        key: "difficultServiceType",
        label: "Difficult Service",
        type: "select",
        required: false,
        group: "Difficult Service (7.5.3)",
        options: ["current", "previous", "none"],
        clearsOnChange: [
          "difficultServiceStartDate",
          "difficultServicePreviousStartDate",
          "difficultServicePreviousEndDate",
          "difficultServiceDistanceStartDate",
          "difficultServiceDistanceEndDate",
          "difficultServiceDistanceKm",
        ],
      },
      {
        key: "difficultServiceStartDate",
        label: "Difficult Service Start",
        type: "date",
        required: false,
        group: "Difficult Service (7.5.3)",
        visibleWhen: [{ field: "difficultServiceType", in: ["current"] }],
      },
      {
        key: "difficultServicePreviousStartDate",
        label: "Previous Difficult Service Start",
        type: "date",
        required: false,
        group: "Difficult Service (7.5.3)",
        visibleWhen: [{ field: "difficultServiceType", in: ["previous"] }],
      },
      {
        key: "difficultServicePreviousEndDate",
        label: "Previous Difficult Service End",
        type: "date",
        required: false,
        group: "Difficult Service (7.5.3)",
        visibleWhen: [{ field: "difficultServiceType", in: ["previous"] }],
      },
      {
        key: "difficultServiceDistanceStartDate",
        label: "Original Station Service Start",
        type: "date",
        required: false,
        group: "Difficult Service (7.5.3)",
        visibleWhen: [{ field: "difficultServiceType", in: ["previous"] }],
      },
      {
        key: "difficultServiceDistanceEndDate",
        label: "Original Station Service End",
        type: "date",
        required: false,
        group: "Difficult Service (7.5.3)",
        visibleWhen: [{ field: "difficultServiceType", in: ["previous"] }],
      },
      {
        key: "difficultServiceDistanceKm",
        label: "Residence to Original Station (km)",
        type: "number",
        required: false,
        group: "Difficult Service (7.5.3)",
        visibleWhen: [{ field: "difficultServiceType", in: ["previous"] }],
      },
      {
        key: "unutilizedLeaveYears",
        label: "Unutilized Leave Years",
        type: "number",
        required: false,
        group: "Leave & Distances (7.5.4+)",
        visibleWhen: [{ field: "contributionPath", in: ["institution"] }],
      },
      {
        key: "residenceToSchoolKm",
        label: "Residence to School (km)",
        type: "number",
        required: false,
        group: "Leave & Distances (7.5.4+)",
      },
      {
        key: "workplaceToSchoolKm",
        label: "Workplace to School (km)",
        type: "number",
        required: false,
        group: "Leave & Distances (7.5.4+)",
      },
    ] satisfies Omit<MarkingFieldDefinition, "step">[]),
  },
  {
    type: "6.5",
    label: "Transfer Applications",
    description: "6.5 — Transfer distance, service periods and map proximity.",
    maxMarks: 100,
    // g1's application-store allows any category type to be added multiple times
    // (entries only need unique ids) — keep that behaviour.
    allowMultipleEntries: true,
    step: "categories",
    fields: withCategoryStep([
      {
        key: "previousWorkplaceDistanceKm",
        label: "Previous-to-New Workplace (km)",
        type: "number",
        required: true,
        group: "Transfer Distance",
      },
      {
        key: "serviceStartDate",
        label: "Period of Service Start",
        type: "date",
        required: false,
        group: "Service Periods",
      },
      {
        key: "previousWorkplaceStartDate",
        label: "Previous Workplace Start",
        type: "date",
        required: false,
        group: "Service Periods",
      },
      {
        key: "transferDate",
        label: "Transfer Date",
        type: "date",
        required: false,
        group: "Service Periods",
      },
      {
        key: "unutilizedLeaveYears",
        label: "Unutilized Leave Years",
        type: "number",
        required: false,
        group: "Service Periods",
      },
      {
        key: "schoolsWithinRadius",
        label: "Nearby Schools (map circle)",
        type: "map",
        required: true,
        group: "Map Proximity",
        mapConfig: { maxMarks: 30, pointsPerSchool: 3, pointsKm: 10 },
      },
    ] satisfies Omit<MarkingFieldDefinition, "step">[]),
  },
  {
    type: "6.6",
    label: "Foreign Employment",
    description:
      "6.6 — Period abroad with the child, purpose and map proximity.",
    maxMarks: 100,
    // g1's application-store allows any category type to be added multiple times
    // (entries only need unique ids) — keep that behaviour.
    allowMultipleEntries: true,
    step: "categories",
    fields: withCategoryStep([
      {
        key: "abroadStartDate",
        label: "Abroad Start",
        type: "date",
        required: true,
        group: "Period Abroad",
      },
      {
        key: "abroadEndDate",
        label: "Abroad End",
        type: "date",
        required: true,
        group: "Period Abroad",
      },
      {
        key: "employmentPurpose",
        label: "Purpose of Foreign Stay",
        type: "select",
        required: true,
        group: "Period Abroad",
        options: ["diplomatic", "government", "education", "employment"],
      },
      {
        key: "schoolsWithinRadius",
        label: "Nearby Schools (map circle)",
        type: "map",
        required: true,
        group: "Map Proximity",
        mapConfig: { maxMarks: 35, pointsPerSchool: 3.5, pointsKm: 10 },
      },
    ] satisfies Omit<MarkingFieldDefinition, "step">[]),
  },
];
